### Input file generated by badapple.py --dbschema $DBSCHEMA --scaf_assay_matrix


ifile <- "~/projects/badapple/data/badapple2_scafscore_vs_assay_matrix.csv"

x <- read.csv(ifile,header=TRUE)


rownames(x) <- x$eid
x$eid <- NULL
x <- as.matrix(x)
scafsums <- colSums(x)
scafrank <- order(scafsums,decreasing=TRUE)
scafsums <- scafsums[scafrank]
print(sprintf("Scaffolds with nonzero activity: %d", length(scafsums[scafsums > 0])))

asysums <- rowSums(x)
asyrank <- order(asysums,decreasing=TRUE)
asysums <- asysums[asyrank]
print(sprintf("Assays with nonzero activity: %d", length(asysums[asysums > 0])))

#myramp <- colorRamp(rev(heat.colors(16)),bias = 1)
myramp <- colorRamp(colorRampPalette(c("red","orange","yellow","gray"))(16), bias=1)

n_asy <- 100
n_scaf <- 200


x_plot <- x[asyrank[1:n_asy],scafrank[1:n_scaf]]
y <- x_plot/max(x_plot)

#heatmap(y,col=myramp(y),Rowv=NA,Colv=NA, main="Scaf-Assay Activity",xlab="Scaffold",ylab="Assay")

library(gplots)

#my_palette <- myramp(y)
my_palette <- colorRampPalette(rev(c("red","orange","yellow","gray")))(n = 16)
heatmap.2(y, main="Scaf-Assay Activity Ratio", xlab="Scaffold", ylab="Assay",
          density.info="none",  # no density plot in legend
          trace="none",
          col=my_palette,
          dendrogram="none")

