#!/bin/sh
#############################################################################
### Go_badapple_DataAnalysis.sh - Analyze and view scaffolds and scores.
### 
### Input CSV (unsorted) from Java badapple app, or can be dumped (sorted) 
### from database.  badapple_analysis.R also sorts by pScore.
### 
### Motivation: publication, slides, etc.
###
### [x] Histogram of scores (TOP_PCT%)
### [~] How much total activity (i.e. compounds|assays|samples active) in TOP_PCT%.
### [~] Cutoff parameter evaluation.
###
### Jeremy Yang
###  8 Jul 2014
#############################################################################
#
if [ `uname -s` = "Linux" ]; then
	#PDFVIEWER="acroread"
	PDFVIEWER="okular"
elif [ `uname -s` = "Darwin" ]; then
	PDFVIEWER="open"
else
	PDFVIEWER="acroread"
fi
#
DBNAME="openchord"
#
if [ $# -lt 1 ]; then
	printf "Syntax: %s DBSCHEMA\n" $0
	exit
fi
#
SCHEMA=$1
#
PREFIX="data/${SCHEMA}"
#
#
#set -x
#
PSCORE_CUTOFF_MODERATE=100
PSCORE_CUTOFF_HIGH=300
#
csvfile=${PREFIX}_scaf_scores.csv
#
#Can be produced with:
#./badapple.sh -v -dbschema ${SCHEMA} -out_scaf ${csvfile}
#
#############################################################################
### Generate CSV file if needed.  Scaffold data in descending pScore order.
### Same content (unsorted) generated by badapple Java app.
#
if [ ! -f "$csvfile" ]; then
	psql \
	--quiet \
	--no-align \
	--field-separator ',' \
	-d $DBNAME \
	-o $csvfile \
	<<__EOF__
SELECT
	scafsmi,
	id,
	ncpd_tested,
	ncpd_active,
	nsub_tested,
	nsub_active,
	nass_tested,
	nass_active,
	nsam_tested,
	nsam_active,
	pscore,
	CASE
		WHEN in_drug THEN 'TRUE' ELSE 'FALSE'
	END
FROM
	$SCHEMA.scaffold
ORDER BY pscore DESC
	;
__EOF__
	#
	### Fix CSV.
	cat $csvfile |sed -e '1d' |sed -e '$d' >data/z.csv
	echo 'scafsmi,id,cTested,cActive,sTested,sActive,aTested,aActive,wTested,wActive,pScore,inDrug' >$csvfile
	cat data/z.csv >>$csvfile
	rm data/z.csv
	#
else
	echo "$csvfile exists; not overwritten."
fi
#
TOP_PCT=5
#
#############################################################################
### Badapple scaffold data analysis using R.
### Now R sorts CSV by pScore/DESC.
#
title_prefix="Badapple Scaffold Promiscuity (${SCHEMA})"
ofile_prefix="${PREFIX}_scaf_topscores_${TOP_PCT}pct"
#
R \
	--quiet --slave \
	-f R/badapple_analysis.R \
	--args $csvfile $ofile_prefix "$title_prefix" \
		$TOP_PCT \
		$PSCORE_CUTOFF_MODERATE \
		$PSCORE_CUTOFF_HIGH
#
$PDFVIEWER ${ofile_prefix}*.pdf &
#
#############################################################################
### Generate top CSV for Excel import.
#
N=`cat $csvfile |wc -l`
N=`expr $N - 1`
N_TOP=`expr $N \* $TOP_PCT / 100`
#
cat $csvfile \
	|sed -e "${N_TOP},\$d" \
	>${PREFIX}_scaf_scores_top${TOP_PCT}pct.csv
#
